### ISSUE TITLE
Can't get addon to work

### ISSUE THREAD

**Issue by st-h** [shipshapecode/ember-meta#37]
I've tried to set up my app as described within the readme. However, it looks like nothing I put into `head.hbs` is actually added to the rendered app. In the end I created a new ember app and followed the readme, however I still can't get it any title or meta tags to update as they should. I can only see the default state. 

This is the test app  I had been creating to reproduce my issue: https://github.com/st-h/ember-meta-test

Additionally I noticed that ember now seems to include ember-page-title per default. Does ember-page-title interfere with this addon? I removed it, but it does not seem to matter. 

**Disclaimer**: I ended up replacing ember-page-title with ember-cli-head and customised `head.hbs` according to my needs, so it includes both the title and needed meta tags, which seems to work nicely.

**Comment by rwwagner90** [comment]
@st-h sorry for the confusion! You have to put `<HeadLayout/>` in your app, just like you do with ember-cli-head, as this uses it under the hood. Perhaps we should explicitly mention that in the README? If you would like to open a PR adding some docs for this, that would be great!

**Comment by st-h** [comment]
@rwwagner90 Thanks a lot for the explanation. However, I decided to not use this addon, as I was able to achieve the same thing by using just `ember-cli-head` and unfortunately my time is very limited at the moment. But I think it should be definitely added to the README, because this seems to be an important step when trying to use this addon.
