### ISSUE TITLE
Proposal · Provide different set of keys used for meta tags

### ISSUE THREAD

**Issue by snewcomer** [shipshapecode/ember-meta#8]
Proposal --

If returning multiple items from a route, allow to return a model under the key `meta`.

So for example...
```
currentRouteModel.meta.articleTitle || currentRouteModel.articleTitle
```

**Comment by rwwagner90** [comment]
This seems logical to me 👍

**Comment by rwwagner90** [comment]
I believe this PR accomplishes this https://github.com/shipshapecode/ember-meta/pull/13

Can we close this @snewcomer?
